### ISSUE TITLE
[FEATURE] Update REST client used in OpenSearchRestTemplate

### ISSUE THREAD

**Issue by curena-contrast** [opensearch-project/spring-data-opensearch#170] opened 2023-10-11 14:45 UTC
### Is your feature request related to a problem?
The client used in `org.opensearch.data.client.orhlc.OpenSearchRestTemplate`, `org.opensearch.client.RestHighLevelClient`, has been deprecated in [Elasticsearch since v7.15](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html). The OpenSearch documentation [also considers it deprecated](https://opensearch.org/docs/latest/clients/java-rest-high-level/).

### What solution would you like?
The `OpenSearchRestTemplate` should use the Java client `org.opensearch.client.opensearch.OpenSearchClient` instead. 

### What alternatives have you considered?
Continuing to use the deprecated client runs the risk of breakage through its removal.

### Do you have any additional context?
No

**Comment by curena-contrast** [comment] 2023-10-11 14:47
Note to maintainers:
Consider adding an issue type that's neither a bug nor an enhancement --  E.g., Technical debt, wherein this particular issue would be more accurately categorized.

**Comment by curena-contrast** [comment] 2023-10-11 14:48
And thanks for this fabulous Spring Data implementation!

**Comment by dblock** [comment] 2023-10-13 18:37
@curena-contrast Want to take this on?

**Comment by reta** [comment] 2023-10-13 19:15
@curena-contrast this is a duplicate of https://github.com/opensearch-project/spring-data-opensearch/issues/19

**Closed by reta** 2023-10-13 19:15 UTC
Labels: enhancement, untriaged
