### ISSUE TITLE
[FEATURE] Provide auto configuration for AWS transport

### ISSUE THREAD

**Issue by hberrayana** [opensearch-project/spring-data-opensearch#267] opened 2024-04-25 12:06 UTC
### Is your feature request related to a problem?

The current opensearch auto configuration doesn't allow auto-creating clients that use the AwsSdk2Transport. 
I'd like to be able to configure my application locally to connect to docker OS instance and use aws opensearch service for the non-local environments.

This change should be possible using predefined properties such as 

```yaml
cloud:
 aws:
   credentials:
     access-key: KEY
     secret-key: SECRET
   region:
     static: us-west-2
     auto: false
opensearch:
  aws-endpoint: search-...us-west-2.es.amazonaws.com
```

On a local environment I should be able to connect to a local O.S cluster without changing my code through a simple configuration:

```yaml
opensearch:
  uris: https://localhost:9200
  username: admin
  password: admin
 
```

### What solution would you like?

The auto configuration should be able to build a proper `OpenSearchClient` instance dependent on the provided configuration parameters.

### What alternatives have you considered?

Creating two `@Configuration` classes but there's a better way to do it.

### Do you have any additional context?

The class [OpenSearchProperties.java](https://github.com/opensearch-project/spring-data-opensearch/blob/main/spring-data-opensearch-starter/src/main/java/org/opensearch/spring/boot/autoconfigure/OpenSearchProperties.java) does not contain any parameter that allows to specify an aws configuration.

The java client documentation provides a guide to connect to opensearch aws service

SdkHttpClient httpClient = ApacheHttpClient.builder().build();

```java
OpenSearchClient client = new OpenSearchClient(
    new AwsSdk2Transport(
        httpClient,
        "search-...us-west-2.es.amazonaws.com", // OpenSearch endpoint, without https://
        "es",
        Region.US_WEST_2, // signing service region
        AwsSdk2TransportOptions.builder().build()
    )
);
```

**Comment by reta** [comment] 2024-05-22 16:45
@hberrayana you should be able to do that now since https://github.com/opensearch-project/spring-data-opensearch/issues/19 has been integrated.

**Comment by dblock** [comment] 2024-06-24 16:25
Closing via #19.

**Closed by dblock** 2024-06-24 16:25 UTC
Labels: enhancement, untriaged

**Comment by Neuw84** [comment] 2024-07-19 08:17
Hi @reta, 

Could you provide an example? I got the integration right with username and password but for Cognito and using HTTP5 ... seems impossible or I don't see how to do it.  

```
  @NonNull
  @Override
  public org.springframework.data.elasticsearch.client.ClientConfiguration clientConfiguration() {

    Aws4Signer signer = Aws4Signer.create();
    Aws4SignerParams signerParams =
            Aws4SignerParams.builder()
                    .signingRegion(Region.of(region))
                    .awsCredentials(credentialsProvider.resolveCredentials())
                    .signingName("es")
                    .build();
    HttpRequestInterceptor interceptor = new AwsRequestSigningApacheV5Interceptor(
            "es",
            signer,
            credentialsProvider,
            Region.of(region)
    );
    ApacheHttpClient5TransportBuilder.HttpClientConfigCallback callback = new ApacheHttpClient5TransportBuilder.HttpClientConfigCallback() {
      @Override
      public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpAsyncClientBuilder) {
        return httpAsyncClientBuilder.addRequestInterceptorLast(interceptor);
      }
    };


    return  org.springframework.data.elasticsearch.client.ClientConfiguration.builder()
            .connectedTo(endpoint)
            .usingSsl()
           .withClientConfigurer(callback) 
**// I would need to add the interceptor here but all the implementors expect http4**
            .withConnectTimeout(Duration.ofSeconds(10))
            .withSocketTimeout(Duration.ofSeconds(5))
            .build();
  }
}
```

All the classes that implement ClientConfigurer from spring-data-open-search implement http 4 and not http 5.... therefore I don't see a way to configure this.

Maybe there is another way to inject the transport options but how I can inject this code...???
`AwsSdk2TransportOptions.builder().build();`

Another possibility is to modify the headers that won't be clean. 

Thanks!!

**Comment by reta** [comment] 2024-07-19 12:49
@Neuw84 sure, so you would need to use `org.opensearch.data.client.osc.OpenSearchConfiguration` (not `AbstractOpenSearchConfiguration`) and configure it using `AwsSdk2Transport` (see please https://github.com/opensearch-project/opensearch-java/blob/main/guides/auth.md#amazon-opensearch-service, which is also referenced in the description):

```
@Configuration
@EnableElasticsearchRepositories(basePackages = "com.aws.samples.opensearch.repository")
@Slf4j
public class OpenSearchAwsClientConfiguration extends OpenSearchConfiguration {

        @Value("${aws.os.endpoint}")
        private String endpoint = "";
      
        @Value("${aws.os.region}")
        private String region = "";
      
        @Value("${aws.os.username}")
        private String username = "";
      
        @Value("${aws.os.password}")
        private String password = "";

       @NonNull
        @Override
        public ClientConfiguration clientConfiguration() {
            return  ClientConfiguration.builder()
                    .connectedTo(endpoint)
                    .usingSsl()
                    .withBasicAuth(username,password)
                    .withConnectTimeout(Duration.ofSeconds(10))
                    .withSocketTimeout(Duration.ofSeconds(5))
                    .build();
        }

        @Override
        public OpenSearchTransport opensearchTransport(RestClient restClient, JsonpMapper jsonpMapper) {    
            SdkHttpClient httpClient = ApacheHttpClient.builder().build();
            return new AwsSdk2Transport(
                    httpClient,
                    endpoint,
                    "es" // signing service name, use "aoss" for OpenSearch Serverless
                    region,
                    AwsSdk2TransportOptions.builder().build()
                );
       }
}
```

**Comment by Neuw84** [comment] 2024-07-19 13:40
Hi! 

Now I have this, 

```
public class OpenSearchRestClientConfiguration extends OpenSearchConfiguration {

  @Value("${aws.os.endpoint}")
  private String endpoint = "";

  @Value("${aws.os.region}")
  private String region = "";

  private StsAssumeRoleCredentialsProvider credentialsProvider = null;

  @Autowired
  public OpenSearchRestClientConfiguration(StsAssumeRoleCredentialsProvider provider) {
    credentialsProvider = provider;
  }

  @NonNull
  @Override
  public ClientConfiguration clientConfiguration() {
    return  ClientConfiguration.builder()
            .connectedTo(endpoint)
            .usingSsl()
            .withConnectTimeout(Duration.ofSeconds(10))
            .withSocketTimeout(Duration.ofSeconds(5))
            .build();
  }

  public OpenSearchTransport opensearchTransport(RestClient restClient, JsonpMapper jsonpMapper) {
    SdkHttpClient httpClient = ApacheHttpClient.builder().build();
    return new AwsSdk2Transport(
            httpClient,
            endpoint,
            "es", // signing service name, use "aoss" for OpenSearch Serverless
            Region.of(region),
            AwsSdk2TransportOptions.builder().setCredentials(credentialsProvider).build()
    );  }
```

The problem is that I can't override the transport as `OpenSearchConfiguration`  does already implement the method. If I debug the `opensearchTransport` is not called and therefore, the application fails as I am not signing the calls to Amazon OpenSearch Service.

My OpenSearchConfiguration class looks like this: 

```
package org.opensearch.data.client.osc;

import org.opensearch.client.RequestOptions;
import org.opensearch.client.RestClient;
import org.opensearch.client.json.JsonpMapper;
import org.opensearch.client.json.jackson.JacksonJsonpMapper;
import org.opensearch.client.opensearch.OpenSearchClient;
import org.opensearch.client.transport.OpenSearchTransport;
import org.opensearch.client.transport.TransportOptions;
import org.opensearch.client.transport.rest_client.RestClientOptions;
import org.springframework.context.annotation.Bean;
import org.springframework.data.elasticsearch.client.ClientConfiguration;
import org.springframework.data.elasticsearch.config.ElasticsearchConfigurationSupport;
import org.springframework.data.elasticsearch.core.ElasticsearchOperations;
import org.springframework.data.elasticsearch.core.convert.ElasticsearchConverter;
import org.springframework.util.Assert;

public abstract class OpenSearchConfiguration extends ElasticsearchConfigurationSupport {
    public OpenSearchConfiguration() {
    }

    @Bean(
        name = {"elasticsearchClientConfiguration"}
    )
    public abstract ClientConfiguration clientConfiguration();

    @Bean
    public RestClient opensearchRestClient(ClientConfiguration clientConfiguration) {
        Assert.notNull(clientConfiguration, "clientConfiguration must not be null");
        return OpenSearchClients.getRestClient(clientConfiguration);
    }

    @Bean
    public OpenSearchTransport opensearchTransport(RestClient restClient, JsonpMapper jsonpMapper) {
        Assert.notNull(restClient, "restClient must not be null");
        Assert.notNull(jsonpMapper, "jsonpMapper must not be null");
        return OpenSearchClients.getOpenSearchTransport(restClient, "imperative", this.transportOptions(), jsonpMapper);
    }

    @Bean
    public OpenSearchClient opensearchClient(OpenSearchTransport transport) {
        Assert.notNull(transport, "transport must not be null");
        return OpenSearchClients.createImperative(transport);
    }

    @Bean(
        name = {"elasticsearchOperations", "elasticsearchTemplate", "opensearchOperations", "opensearchTemplate"}
    )
    public ElasticsearchOperations opensearchOperations(ElasticsearchConverter elasticsearchConverter, OpenSearchClient elasticsearchClient) {
        OpenSearchTemplate template = new OpenSearchTemplate(elasticsearchClient, elasticsearchConverter);
        template.setRefreshPolicy(this.refreshPolicy());
        return template;
    }

    @Bean
    public JsonpMapper jsonpMapper() {
        return new JacksonJsonpMapper();
    }

    public TransportOptions transportOptions() {
        return new RestClientOptions(RequestOptions.DEFAULT);
    }
}
```


Thanks for your help, very appreciated!

**Comment by reta** [comment] 2024-07-19 14:08
> The problem is that I can't override the transport as `OpenSearchConfiguration` does already implement the method.

This is not an issue, the method is not `final` and could be overridden. I don't see `@Configuration` on your `OpenSearchRestClientConfiguration` class

**Comment by Neuw84** [comment] 2024-07-19 14:16
The full class, If I use @override (sorry, long time Java user but I forgot the basics sometimes 🥇 ) is weird as I get 

`method does not override or implement a method from a supertype
`
On the compiler, the full Java class is like this: 

```

import java.time.Duration;

import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import org.opensearch.client.json.JsonpMapper;
import org.opensearch.client.transport.OpenSearchTransport;
import org.opensearch.client.transport.aws.AwsSdk2Transport;
import org.opensearch.client.transport.aws.AwsSdk2TransportOptions;
import org.opensearch.data.client.osc.OpenSearchConfiguration;
import org.springframework.data.elasticsearch.client.ClientConfiguration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.elasticsearch.repository.config.EnableElasticsearchRepositories;
import org.springframework.web.client.RestClient;
import software.amazon.awssdk.http.SdkHttpClient;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider;


@Configuration
@EnableElasticsearchRepositories(basePackages = "com.aws.samples.opensearch.repository")
@Slf4j
public class OpenSearchRestClientConfiguration extends OpenSearchConfiguration {

  @Value("${aws.os.endpoint}")
  private String endpoint = "";

  @Value("${aws.os.region}")
  private String region = "";

  private StsAssumeRoleCredentialsProvider credentialsProvider = null;

  @Autowired
  public OpenSearchRestClientConfiguration(StsAssumeRoleCredentialsProvider provider) {
    credentialsProvider = provider;

  }

  @NonNull
  @Override
  public ClientConfiguration clientConfiguration() {
    Aws4Signer signer = Aws4Signer.create();
    Aws4SignerParams signerParams =
            Aws4SignerParams.builder()
                    .signingRegion(Region.of(region))
                    .awsCredentials(credentialsProvider.resolveCredentials())
                    .signingName("es")
                    .build();
    HttpRequestInterceptor interceptor = new AwsRequestSigningApacheV5Interceptor(
            "es",
            signer,
            credentialsProvider,
            Region.of(region)
    );

    return ClientConfiguration.builder()
        .connectedTo(endpoint)
        .usingSsl()
        .withConnectTimeout(Duration.ofSeconds(10))
        .withSocketTimeout(Duration.ofSeconds(5))
        .build();
  }


  @Override
  public OpenSearchTransport opensearchTransport(RestClient restClient, JsonpMapper jsonpMapper) {
    SdkHttpClient httpClient = ApacheHttpClient.builder().build();
    return new AwsSdk2Transport(
            httpClient,
            endpoint,
            "es", // signing service name, use "aoss" for OpenSearch Serverless
            Region.of(region),
            AwsSdk2TransportOptions.builder().setCredentials(credentialsProvider).build()
    );  
  }



}


```

**Comment by reta** [comment] 2024-07-19 14:30
Please check  the method signature

 `import org.springframework.web.client.RestClient;` 

is not the OpenSearch `RestClient` but it should be.

**Comment by Neuw84** [comment] 2024-07-19 16:08
Ok, thanks!

The problem was that I didn't have the opensearch-rest-client libraries and the default import was Spring... 

```
  <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>spring-data-opensearch</artifactId>
            <version>1.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.opensearch.client</groupId>
                    <artifactId>opensearch-rest-high-level-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>opensearch-rest-client</artifactId>
            <version>2.15.0</version>
        </dependency>
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>opensearch-java</artifactId>
            <version>2.11.1</version>
        </dependency>
```

Reading #19 I need those two clients until open-search java catches up, no? 

Let me know if I could help on finishing the merge. 

I will also update the code on the repo that I have. 

https://github.com/aws-samples/opensearch-bootful

**Comment by reta** [comment] 2024-07-19 16:15
> The problem was that I didn't have the opensearch-rest-client libraries and the default import was Spring...

Ah, this is unexpected

> Reading https://github.com/opensearch-project/spring-data-opensearch/issues/19 I need those two clients until open-search java catches up, no?

Yes, we need both for now, I will update the documentation, thank you
